### ISSUE TITLE
Migration to new transifex API

### ISSUE THREAD

**Issue by Docteh** [zhaowenlan1779/txbot#2]
Transifex is turning off the API for the python client at the end of the month

Over on yuzu I  filed a PR https://github.com/yuzu-emu/yuzu/pull/9058

This PR https://github.com/yuzu-emu/build-environments/pull/62 shows how tx client is grabbed for the container

If you do follow suggested installation manner, ensure that the current working dir is okay to be added to path
`curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash` 

There is no forwards/backwards compatibility in `.tx/config` 🤦‍♂️ (this is where things broke down)

For github actions yuzu switched to using TX_TOKEN for the environment variable holding API token, because `~/.transifexrc` was not working on github actions, but the client [fixed this bug](https://github.com/transifex/cli/issues/109)

```diff
diff --git a/dist/languages/.tx/config b/dist/languages/.tx/config
index 0d9b512ea60c..30e76b92596f 100644
--- a/dist/languages/.tx/config
+++ b/dist/languages/.tx/config
@@ -1,7 +1,7 @@
 [main]
 host = https://www.transifex.com
 
-[yuzu.emulator]
+[o:yuzu-emulator:p:yuzu:r:emulator]
 file_filter = <lang>.ts
 source_file = en.ts
 source_lang = en
```

**Comment by Docteh** [comment]
Instead of "tx pull -a --minimum-perc 47", on my Windows computer I had to use  `tx pull -a -t -f --minimum-perc 47` to get it to actually download all files, otherwise it thought that the local files were too new.

**Comment by zhaowenlan1779** [comment]
Thank you. I  will look into this shortly

**Comment by zhaowenlan1779** [comment]
Should be fixed now
